Set _POSIX_C_SOURCE to 200809L
Otherwise string.h doesn't include strdup and we get the following warning.

src/net.c:208:15: warning: implicit declaration of function 'strdup' is invalid in C99 [-Wimplicit-function-declaration]
    *hostnm = strdup(host->h_name);